# Array test formatter

This is the array version for UI formatting.

The cells contain a version of json data, css and html that produce a decent output.

The code to generate this is under development.

In [ ]:
#!csharp
// These are raw jspon strings used to generate a sample array and an object.
string arrayJson = "[{\"LocationName\":\"Prohaskabury\",\"TelephoneNumbers\":[\"1-991-882-5369 x51296\",\"(553) 867-5766\"],\"AddressRows\":[\"0243 Cordie Radial\",\"97240 Fay Ramp\"],\"EmployeeCount\":2,\"Employees\":[{\"Id\":1000,\"Name\":\"Sean Schumm\",\"Title\":\"Principal Accounts Assistant\",\"Email\":\"Patsy.Turner2@hotmail.com\",\"Telephone\":\"785-889-4561 x015\"},{\"Id\":1001,\"Name\":\"Prince Morar\",\"Title\":\"Principal Identity Technician\",\"Email\":\"Anjali80@gmail.com\",\"Telephone\":\"(211) 545-7142\"}]},{\"LocationName\":\"Port Celestino\",\"TelephoneNumbers\":[\"1-560-495-5164 x463\",\"752-986-7930 x475\"],\"AddressRows\":[\"465 Lenore Station\",\"73389 Jodie Hills\"],\"EmployeeCount\":3,\"Employees\":[{\"Id\":1002,\"Name\":\"Darius Mohr\",\"Title\":\"District Response Consultant\",\"Email\":\"Margot_Romaguera@gmail.com\",\"Telephone\":\"1-928-582-0578\"},{\"Id\":1003,\"Name\":\"Edwin Mayer\",\"Title\":\"Forward Communications Director\",\"Email\":\"Dandre94@yahoo.com\",\"Telephone\":\"966-393-9472\"},{\"Id\":1004,\"Name\":\"Johathan Williamson\",\"Title\":\"Human Program Producer\",\"Email\":\"Aiyana.Macejkovic6@hotmail.com\",\"Telephone\":\"(936) 300-5854\"}]}]";
string objectJson = "{\"Client\":\"Nienow - Schiller\",\"Size\":2,\"LocationCount\":2,\"Locations\":[{\"LocationName\":\"Prohaskabury\",\"TelephoneNumbers\":[\"1-991-882-5369 x51296\",\"(553) 867-5766\"],\"AddressRows\":[\"0243 Cordie Radial\",\"97240 Fay Ramp\"],\"EmployeeCount\":2,\"Employees\":[{\"Id\":1000,\"Name\":\"Sean Schumm\",\"Title\":\"Principal Accounts Assistant\",\"Email\":\"Patsy.Turner2@hotmail.com\",\"Telephone\":\"785-889-4561 x015\"},{\"Id\":1001,\"Name\":\"Prince Morar\",\"Title\":\"Principal Identity Technician\",\"Email\":\"Anjali80@gmail.com\",\"Telephone\":\"(211) 545-7142\"}]},{\"LocationName\":\"Port Celestino\",\"TelephoneNumbers\":[\"1-560-495-5164 x463\",\"752-986-7930 x475\"],\"AddressRows\":[\"465 Lenore Station\",\"73389 Jodie Hills\"],\"EmployeeCount\":3,\"Employees\":[{\"Id\":1002,\"Name\":\"Darius Mohr\",\"Title\":\"District Response Consultant\",\"Email\":\"Margot_Romaguera@gmail.com\",\"Telephone\":\"1-928-582-0578\"},{\"Id\":1003,\"Name\":\"Edwin Mayer\",\"Title\":\"Forward Communications Director\",\"Email\":\"Dandre94@yahoo.com\",\"Telephone\":\"966-393-9472\"},{\"Id\":1004,\"Name\":\"Johathan Williamson\",\"Title\":\"Human Program Producer\",\"Email\":\"Aiyana.Macejkovic6@hotmail.com\",\"Telephone\":\"(936) 300-5854\"}]}]}";
arrayJson.Display();
objectJson.Display();

In [ ]:
// Initialize the razor and Json environments
#r "nuget:Newtonsoft.Json"
#r "nuget:RazorEngine.NetCore"

In [ ]:
#!html

/* This code wwas used in https://jsfiddle.net/zyqsmu6h/ to test the array Display */
/* It isn't right though, as it doesn't present the array opf properties correctly */

<!DOCTYPE html>
<html>
<head>
<style>
.red {
    color: red !important;
  }
  
  .blue {
    color: blue !important;
    background-color: darkblue !important;
  }
  
  
  body {
    --data-text: #cccccc;
    --data-background-even: #1f1f1f;
    --data-background-odd: #111;
    --name-text: #888888;
    --name-background-even: #2c2c2c;
    --name-background-odd: #222222;
    --head-text: #888888;
    --head-background: #2c2c2c;
    --box-low: #888888;
    --box-high: #aaaaaa;
  }
  
  * {
    margin: 0;
    padding: 0;
  }
  
  .containerx {
    /* This is the container for the table, use this to limit the width */
    max-width: 800px;
    margin: auto;
    margin-top: 3rem;
    overflow-x: auto;
  }
  
  .tablex {
    /* This is the table */
    font-family: "Open Sans", sans-serif !important;
    position: relative !important;
    border-collapse: collapse !important;
    border-spacing: 0 !important;
    table-layout: auto !important;
    max-width: 100% !important;
    border: none !important;
    white-space: nowrap !important;
  
    * {
      border: none !important;
    }
  
    .trx td {
      /* This is needed on each table row */
      min-width: 25%;
      max-width: 500px !important;
      word-wrap: break-word !important;
      color: var(--data-text);
      padding: 3px 5px;
      vertical-align: top;
      text-align: left;
      font-size: 1.125rem;
      font-weight: normal;
      white-space: nowrap;
    }
  }
  
  .lj {
    /* This is typical data cell - you can limit the width here.*/
    text-align: left;
    font-family: "consolas", monospace;
  
    min-width: 25%;
    max-width: 500px;
    word-wrap: break-word;
    overflow: hidden;
  }
  
  .trx:nth-child(even) td {
    /* This is the even row */
    background-color: var(--data-background-even) !important;
  }
  
  .trx:nth-child(odd) td {
    /* This is the odd row */
    background-color: var(--data-background-odd) !important;
  }
  
  .trx:nth-child(even) .lh {
    /* This is the left-hand column, used for the headers */
    position: sticky;
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: right;
    color: var(--name-text);
    left: 0;
    white-space: nowrap;
    background-color: var(--name-background-even) !important;
  }
  
  .trx:nth-child(odd) .lh {
    /* This is the left-hand column, used for the headers */
    position: sticky;
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: right;
    color: var(--name-text);
    white-space: nowrap;
    left: 0;
    background-color: var(--name-background-odd) !important;
  }
  
  .th {
    /* This is the header row */
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: left;
    color: var(--head-text);
    background-color: var(--head-background) !important;
    white-space: nowrap;
    top: 0;
  }
  
  /* The sub puts a subtle box around the element, which highlights on hover. */
  .sub {
    margin: 1px !important;
    box-shadow: 0 0 1px var(--box-low) !important;
    max-width: 500px;
  }
  
  .sub:hover {
    box-shadow: 0 0 2px var(--box-high) !important;
  }
  
  .sc {
    overflow-x: auto;
    max-width: 100%;
    display: block;
  }
</style>
</head>
<body>  
<h1>Array display working okay</h1>
<div class="containerx">
  <table class="tablex sub">
    <tr class="trx">
      <th class="lh">[2 items]</th>
      <th class="th">1</th>
      <th class="th">2</th>
    </tr>
    <tr class="trx">
      <td class="lj">
        <table class="tablex sub sc">
          <tr class="trx">
            <th class="lh">1/2:</th>
            <th class="lh">{5 properties}</th>
          </tr>
          <tr class="trx">
            <td class="lh">LocationName</td>
            <td class="lj">Prohaskabury</td>
          </tr>
          <tr class="trx">
            <td class="lh">TelephoneNumbers</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">AddressRows</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">EmployeeCount</td>
            <td class="lj">2</td>
          </tr>
          <tr class="trx">
            <td class="lh">Employees</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[2 items]</th>
                  <th class="th">1</th>
                  <th class="th">2</th>
                </tr>
                <tr class="trx">
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">1/2:</th>
                        <th class="lh">5 properties</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1000</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Sean Schumm</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Principal Accounts Assistant</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Patsy.Turner2@hotmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">785-889-4561 x015</td>
                      </tr>
                    </table>
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">2/2:</th>
                        <th class="lh">5 properties</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1001</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Prince Morar</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Principal Identity Technician</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Anjali80@gmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">(211) 545-7142</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
      <td class="lj">
        <table class="tablex sub sc">
          <tr class="trx">
            <th class="lh">2/2:</th>
            <th class="lh">{5 properties}</th>
          </tr>
          <tr class="trx">
            <td class="lh">LocationName</td>
            <td class="lj">Port Celestino</td>
          </tr>
          <tr class="trx">
            <td class="lh">TelephoneNumbers</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">TelephoneNumbers [0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">AddressRows</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">EmployeeCount</td>
            <td class="lj">3</td>
          </tr>
          <tr class="trx">
            <td class="lh">Employees</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[3 items]</th>
                  <th class="th">0</th>
                  <th class="th">1</th>
                  <th class="th">2</th>
                </tr>
                <tr class="trx">
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">1/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1002</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Darius Mohr</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">District Response Consultant</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">
                        <td class="lj">Margot_Romaguera@gmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">1-928-582-0578</td>
                      </tr>
                    </table>
                  </td>
                  <td>
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">2/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1003</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Edwin Mayer</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Forward Communications Director</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Dandre94@yahoo.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">966-393-9472</td>
                      </tr>
                    </table>
                  </td>
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">3/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1004</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Johathan Williamson</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Human Program Producer</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Aiyana.Macejkovic6@hotmail.com</td>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">(936) 300-5854</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>
</body>
</html>

In [1]:
#!html

/* This is amodified version, adjytsed to work correctly for a stringly-typed array of objects */

<!DOCTYPE html>
<html>
<head>
<style>
.red {
    color: red !important;
  }
  
  .blue {
    color: blue !important;
    background-color: darkblue !important;
  }
  
  
  body {
    --data-text: #cccccc;
    --data-background-even: #1f1f1f;
    --data-background-odd: #111;
    --name-text: #888888;
    --name-background-even: #2c2c2c;
    --name-background-odd: #222222;
    --head-text: #888888;
    --head-background: #2c2c2c;
    --box-low: #888888;
    --box-high: #aaaaaa;
  }
  
  * {
    margin: 0;
    padding: 0;
  }
  
  .containerx {
    /* This is the container for the table, use this to limit the width */
    max-width: 800px;
    margin: auto;
    margin-top: 3rem;
    overflow-x: auto;
  }
  
  .tablex {
    /* This is the table */
    font-family: "Open Sans", sans-serif !important;
    position: relative !important;
    border-collapse: collapse !important;
    border-spacing: 0 !important;
    table-layout: auto !important;
    max-width: 100% !important;
    border: none !important;
    white-space: nowrap !important;
  
    * {
      border: none !important;
    }
  
    .trx td {
      /* This is needed on each table row */
      min-width: 25%;
      max-width: 500px !important;
      word-wrap: break-word !important;
      color: var(--data-text);
      padding: 3px 5px;
      vertical-align: top;
      text-align: left;
      font-size: 1.125rem;
      font-weight: normal;
      white-space: nowrap;
    }
  }
  
  .lj {
    /* This is typical data cell - you can limit the width here.*/
    text-align: left;
    font-family: "consolas", monospace;
  
    min-width: 25%;
    max-width: 500px;
    word-wrap: break-word;
    overflow: hidden;
  }
  
  .trx:nth-child(even) td {
    /* This is the even row */
    background-color: var(--data-background-even) !important;
  }
  
  .trx:nth-child(odd) td {
    /* This is the odd row */
    background-color: var(--data-background-odd) !important;
  }
  
  .trx:nth-child(even) .lh {
    /* This is the left-hand column, used for the headers */
    position: sticky;
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: right;
    color: var(--name-text);
    left: 0;
    white-space: nowrap;
    background-color: var(--name-background-even) !important;
  }
  
  .trx:nth-child(odd) .lh {
    /* This is the left-hand column, used for the headers */
    position: sticky;
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: right;
    color: var(--name-text);
    white-space: nowrap;
    left: 0;
    background-color: var(--name-background-odd) !important;
  }
  
  .th {
    /* This is the header row */
    font-family: "consolas", monospace;
    font-style: italic;
    font-size: 85%;
    text-align: left;
    color: var(--head-text);
    background-color: var(--head-background) !important;
    white-space: nowrap;
    top: 0;
  }
  
  /* The sub puts a subtle box around the element, which highlights on hover. */
  .sub {
    margin: 1px !important;
    box-shadow: 0 0 1px var(--box-low) !important;
    max-width: 500px;
  }
  
  .sub:hover {
    box-shadow: 0 0 2px var(--box-high) !important;
  }
  
  .sc {
    overflow-x: auto;
    max-width: 100%;
    display: block;
  }
</style>
</head>
<body>  
<h1>Array display working okay</h1>
<div class="containerx">
  <table class="tablex sub">
    <tr class="trx">
      <th class="lh">[2 items]</th>
      <th class="th">1</th>
      <th class="th">2</th>
    </tr>
          <tr class="trx">
            <th class="lh">1/2:</th>
            <th class="lh">{5 properties}</th>
          </tr>
          <tr class="trx">
            <td class="lh">LocationName</td>
            <td class="lj">Prohaskabury</td>

          </tr>
          <tr class="trx">
            <td class="lh">TelephoneNumbers</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">AddressRows</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">EmployeeCount</td>
            <td class="lj">2</td>
          </tr>
          <tr class="trx">
            <td class="lh">Employees</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[2 items]</th>
                  <th class="th">1</th>
                  <th class="th">2</th>
                </tr>
                <tr class="trx">
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">1/2:</th>
                        <th class="lh">5 properties</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1000</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Sean Schumm</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Principal Accounts Assistant</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Patsy.Turner2@hotmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">785-889-4561 x015</td>
                      </tr>
                    </table>
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">2/2:</th>
                        <th class="lh">5 properties</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1001</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Prince Morar</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Principal Identity Technician</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Anjali80@gmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">(211) 545-7142</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              
            </td>
          </tr>
        </table>
      </td>
      <td class="lj">
        <table class="tablex sub sc">
          <tr class="trx">
            <th class="lh">2/2:</th>
            <th class="lh">{5 properties}</th>
          </tr>
          <tr class="trx">
            <td class="lh">LocationName</td>
            <td class="lj">Port Celestino</td>
          </tr>
          <tr class="trx">
            <td class="lh">TelephoneNumbers</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">TelephoneNumbers [0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">AddressRows</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[0 items]</th>
                </tr>
                <tr class="trx"></tr>
              </table>
            </td>
          </tr>
          <tr class="trx">
            <td class="lh">EmployeeCount</td>
            <td class="lj">3</td>
          </tr>
          <tr class="trx">
            <td class="lh">Employees</td>
            <td class="lj">
              <table class="tablex sub sc">
                <tr class="trx">
                  <th class="lh">[3 items]</th>
                  <th class="th">0</th>
                  <th class="th">1</th>
                  <th class="th">2</th>
                </tr>
                <tr class="trx">
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">1/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1002</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Darius Mohr</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">District Response Consultant</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">
                        <td class="lj">Margot_Romaguera@gmail.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">1-928-582-0578</td>
                      </tr>
                    </table>
                  </td>
                  <td>
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">2/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1003</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Edwin Mayer</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Forward Communications Director</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Dandre94@yahoo.com</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">966-393-9472</td>
                      </tr>
                    </table>
                  </td>
                  <td class="lj">
                    <table class="tablex sub sc">
                      <tr class="trx">
                        <th class="lh">3/3:</th>
                        <th class="lh">{5 properties}</th>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Id</td>
                        <td class="lj">1004</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Name</td>
                        <td class="lj">Johathan Williamson</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Title</td>
                        <td class="lj">Human Program Producer</td>
                      </tr>
                      <tr class="trx">
                        <td class="lh">Email</td>
                        <td class="lj">Aiyana.Macejkovic6@hotmail.com</td>
                      <tr class="trx">
                        <td class="lh">Telephone</td>
                        <td class="lj">(936) 300-5854</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>
</body>
</html>